export const createTable = [
'CREATE TABLE IF NOT EXISTS tb_Marca (id integer NOT NULL CONSTRAINT tb_Marca_pk PRIMARY KEY,'
    +'codigo nvarchar(20) NOT NULL UNIQUE,'
    +'dsMarca nvarchar(80) NOT NULL UNIQUE,'
    +'origem nvarchar(20),'
    +'status boolean NOT NULL,'
    +'dtInsercao datetime,'
    +'dtAlteracao datetime NOT NULL,'
    +'usuarioLogin nvarchar(20),'
    +'deleted boolean)', 
'CREATE TABLE IF NOT EXISTS tb_ControleSyncIn (id integer NOT NULL CONSTRAINT tb_ControleSyncIn_pk PRIMARY KEY,'
    +'tb_Marca datetime,'
    +'tb_Patrimonio datetime,'
    +'tb_Inventario datetime,'
    +'tb_CentroCusto datetime,'
    +'tb_Local datetime,'
    +'tb_Filial datetime,'
    +'tb_CondicaoUso datetime,'
    +'tb_Grupo datetime,'
    +'tb_Propriedade datetime,'
    +'tb_CentroResponsabilidade datetime,'
    +'tb_Especie datetime,'
    +'tb_DicionarioEspecie datetime,'
    +'tb_AtributosDoBem datetime,'
    +'tb_InventarioMovimentacoes datetime,'
    +'tb_PropriedadeLookUp datetime,'
    +'tb_TipoDado datetime,'
    +'tb_TipoDadosPatrimonio datetime,'
    +'tb_FotoDoBem datetime,'
    +'tb_ControleExclusao datetime)',
'CREATE TABLE IF NOT EXISTS tb_ControleSyncOut (id integer NOT NULL CONSTRAINT tb_ControleSyncOut_pk PRIMARY KEY,'
    +'tb_FotoDoBem datetime,'
    +'tb_UsuarioEquipamento datetime,'
    +'tb_InventarioMovimentacoes datetime,'
    +'tb_AtributosDoBem datetime,'
    +'tb_Inventario datetime,'
    +'tb_Patrimonio datetime,'
    +'fotos datetime,'
    +'tb_ConfiguracoesEquipamento datetime,'
    +'tb_Filial datetime,'
    +'tb_Local datetime,'
    +'tb_CentroCusto datetime,'
    +'tb_CentroResponsabilidade datetime)',
'CREATE TABLE IF NOT EXISTS tb_CentroCusto (id integer NOT NULL CONSTRAINT tb_CentroCusto_pk PRIMARY KEY,'
    +'codigo nvarchar(20) NOT NULL UNIQUE,'
    +'nome nvarchar(150),'
    +'situacao nvarchar(20),'
    +'status boolean,'
    +'dtInsercao datetime,'
    +'dtAlteracao datetime,'
    +'usuarioConfigLogin nvarchar(20),'
    +'usuarioPdaLogin nvarchar(20))',
'CREATE TABLE IF NOT EXISTS tb_CentroResponsabilidade (id integer NOT NULL CONSTRAINT tb_CentroResponsabilidade_pk PRIMARY KEY,'
    +'codigo nvarchar(20) NOT NULL UNIQUE,'
    +'nome nvarchar(150),'
    +'situacao nvarchar(20),'
    +'status boolean,'
    +'dtInsercao datetime,'
    +'dtAlteracao datetime,'
    +'usuarioConfigLogin nvarchar(20),'
    +'usuarioPdaLogin nvarchar(20))',
'CREATE TABLE IF NOT EXISTS tb_CondicaoUso (id integer NOT NULL CONSTRAINT tb_CondicaoUso_pk PRIMARY KEY,'
    +'codigo nvarchar(20) NOT NULL UNIQUE,'
    +'nome nvarchar(150),'
    +'situacao nvarchar(20),'
    +'status boolean,'
    +'dtInsercao datetime,'
    +'dtAlteracao datetime,'
    +'usuarioConfigLogin nvarchar(20),'
    +'usuarioPdaLogin nvarchar(20))',
'CREATE TABLE IF NOT EXISTS tb_Grupo (id integer NOT NULL CONSTRAINT tb_Grupo_pk PRIMARY KEY,'
    +'codigo nvarchar(20) NOT NULL UNIQUE,'
    +'nome nvarchar(150),'
    +'situacao nvarchar(20),'
    +'status boolean,'
    +'dtInsercao datetime,'
    +'dtAlteracao datetime,'
    +'usuarioConfigLogin nvarchar(20),'
    +'usuarioPdaLogin nvarchar(20))',
'CREATE TABLE IF NOT EXISTS tb_Especie (id integer NOT NULL CONSTRAINT tb_Especie_pk PRIMARY KEY,'
    +'codigo nvarchar(20) NOT NULL UNIQUE,'
    +'nome nvarchar(150),'
    +'situacao nvarchar(20),'
    +'status boolean,'
    +'dtInsercao datetime,'
    +'dtAlteracao datetime,'
    +'usuarioConfigLogin nvarchar(20),'
    +'usuarioPdaLogin nvarchar(20),'
    +'id_grupo integer,'
    +'codContaContabil nvarchar(21),'
    +'vidaUtil integer,'
    +'CONSTRAINT FK_tb_Especie_tb_Grupo FOREIGN KEY (id_grupo) REFERENCES tb_Grupo(id))',
'CREATE TABLE IF NOT EXISTS tb_Filial (id integer NOT NULL CONSTRAINT tb_Filial_pk PRIMARY KEY,'
    +'codigo nvarchar(20) NOT NULL UNIQUE,'
    +'nome nvarchar(150),'
    +'situacao nvarchar(20),'
    +'status boolean,'
    +'dtInsercao datetime,'
    +'dtAlteracao datetime,'
    +'UsuarioConfigLogin nvarchar(20),'
    +'UsuarioPdaLogin nvarchar(20))',
'CREATE TABLE IF NOT EXISTS tb_LinkEspecieMarca (id integer NOT NULL CONSTRAINT tb_LinkEspecieMarca_pk PRIMARY KEY,'
	+'id_Especie integer NOT NULL UNIQUE,'
	+'id_Marca integer NOT NULL UNIQUE,'
	+'temp boolean NOT NULL,'
	+'retirar boolean NOT NULL,'
	+'CONSTRAINT FK_tb_LinkEspecieMarca_tb_Especie FOREIGN KEY (id_Especie) REFERENCES tb_Especie(id),'
	+'CONSTRAINT FK_tb_LinkEspecieMarca_tb_Marca FOREIGN KEY (id_Marca) REFERENCES tb_Marca(id))',
'CREATE TABLE IF NOT EXISTS tb_Modelo (id integer NOT NULL CONSTRAINT tb_Modelo_pk PRIMARY KEY,'
	+'codigo nvarchar(20) NOT NULL UNIQUE,'
	+'dsModelo nvarchar(80) NOT NULL UNIQUE,'
	+'origem nvarchar(20),'
	+'status boolean NOT NULL,'
	+'dtInsercao datetime,'
	+'usuarioConfigLogin nvarchar(20),'
	+'usuarioPdaLogin nvarchar(20))',
'CREATE TABLE IF NOT EXISTS tb_LinkEspecieMarcaModelo (id integer NOT NULL CONSTRAINT tb_LinkEspecieMarcaModelo_pk PRIMARY KEY,'
    +'id_LinkEspecieMarca int NOT NULL UNIQUE,'
	+'id_Modelo int NOT NULL UNIQUE,'
	+'temp boolean NOT NULL,'
	+'retirar boolean NOT NULL,'
	+'CONSTRAINT FK_tb_LinkEspecieMarcaModelo_tb_LinkEspecieMarca FOREIGN KEY (id_LinkEspecieMarca) REFERENCES tb_LinkEspecieMarca(id),'
	+'CONSTRAINT FK_tb_LinkEspecieMarcaModelo_tb_Modelo FOREIGN KEY (id_Modelo) REFERENCES tb_Modelo(id))',
'CREATE TABLE IF NOT EXISTS tb_Local (id integer NOT NULL CONSTRAINT tb_Local_pk PRIMARY KEY,'
	+'codigo nvarchar(20) NOT NULL UNIQUE,'
	+'nome nvarchar(150),'
	+'situacao nvarchar(20),'
	+'status boolean,'
    +'dtInsercao datetime,'
    +'dtAlteracao datetime,'
	+'usuarioConfigLogin nvarchar(20),'
	+'usuarioPdaLogin nvarchar(20))',
'CREATE TABLE IF NOT EXISTS tb_Patrimonio (id integer NOT NULL CONSTRAINT tb_Patrimonio_pk PRIMARY KEY,'
    +'id_Filial integer NOT NULL,'
    +'id_Especie integer,'
    +'id_Condicao integer,'
    +'id_Responsavel integer,'
    +'id_CentroCusto integer,'
    +'id_Local integer,'
    +'codigo nvarchar(20) NOT NULL,'
    +'codigoAnterior nvarchar(20),'
    +'incorporacao integer,'
    +'incorporacaoAnterior integer,'
    +'descricao nvarchar(255),'
    +'serie nvarchar(80),'
    +'observacao nvarchar(255),'
    +'tag nvarchar(80),'
    +'AUX1 nvarchar(80),'
    +'AUX2 nvarchar(80),'
    +'AUX3 nvarchar(80),'
    +'AUX4 nvarchar(80),'
    +'AUX5 nvarchar(80),'
    +'AUX6 nvarchar(80),'
    +'AUX7 nvarchar(80),'
    +'AUX8 nvarchar(80),'
    +'status nvarchar(26),'
    +'latitude nvarchar(30),'
    +'longitude nvarchar(30),'
    +'altitude nvarchar(30),'
    +'seq integer,'
    +'gravado boolean,'
    +'numeroFicticio integer,'
    +'id_linkEspecieMarca integer,'
    +'id_linkEspecieMarcaModelo integer,'
    +'marca nvarchar(80),'
    +'modelo nvarchar(80),'
    +'dtAlteracao datetime,'
    +'ultimoUsuario nvarchar(50),'
    +'CONSTRAINT FK_tb_Patrimonio_tb_CentroCusto FOREIGN KEY (id_CentroCusto) REFERENCES tb_CentroCusto(id),'
    +'CONSTRAINT FK_tb_Patrimonio_tb_CentroResponsabilidade FOREIGN KEY (id_Responsavel) REFERENCES tb_CentroResponsabilidade(id),'
    +'CONSTRAINT FK_tb_Patrimonio_tb_CondicaoUso FOREIGN KEY (id_Condicao) REFERENCES tb_CondicaoUso(id),'
    +'CONSTRAINT FK_tb_Patrimonio_tb_Especie FOREIGN KEY (id_Especie) REFERENCES tb_Especie(id),'
    +'CONSTRAINT FK_tb_Patrimonio_tb_Filial FOREIGN KEY (id_Filial) REFERENCES tb_Filial(id),'
    +'CONSTRAINT FK_tb_Patrimonio_tb_LinkEspecieMarca FOREIGN KEY (id_linkEspecieMarca) REFERENCES tb_LinkEspecieMarca(id),'
    +'CONSTRAINT FK_tb_Patrimonio_tb_LinkEspecieMarcaModelo FOREIGN KEY (id_linkEspecieMarcaModelo) REFERENCES tb_LinkEspecieMarcaModelo(id),'
    +'CONSTRAINT FK_tb_Patrimonio_tb_Local FOREIGN KEY (id_Local) REFERENCES tb_Local(id))',
'CREATE TABLE IF NOT EXISTS tb_Propriedade (id integer NOT NULL CONSTRAINT tb_Propriedade_pk PRIMARY KEY,'
    +'codigo nvarchar(20),'
    +'nome nvarchar(150),'
    +'situacao nvarchar(20),'
    +'status boolean,'
    +'dtInsercao datetime,'
    +'dtAlteracao datetime,'
    +'usuarioConfigLogin nvarchar(20),'
    +'usuarioPdaLogin nvarchar(20),'
    +'id_tipoDado integer,'
    +'padronizacao nvarchar(255))',
'CREATE TABLE IF NOT EXISTS tb_Inventario (id integer NOT NULL CONSTRAINT tb_Inventario_pk PRIMARY KEY,'
    +'id_patrimonio integer,'
    +'dtInsercao datetime,'
    +'situacao nvarchar(1),'
    +'usuarioPdaLogin nvarchar(20),'
    +'usuarioConfigLogin nvarchar(20))',
'CREATE TABLE IF NOT EXISTS tb_DicionarioEspecie (id integer NOT NULL CONSTRAINT tb_DicionarioEspecie_pk PRIMARY KEY,'
    +'id_grupo integer,'
    +'id_propriedade integer,'
    +'temp boolean,'
    +'retirar boolean,'
    +'CONSTRAINT FK_tb_DicionarioEspecie_tb_Grupo FOREIGN KEY (id_grupo) REFERENCES tb_Grupo(id),'
    +'CONSTRAINT FK_tb_DicionarioEspecie_tb_Propriedade FOREIGN KEY (id_propriedade) REFERENCES tb_Propriedade(id))',
'CREATE TABLE IF NOT EXISTS tb_AtributosDoBem (id integer NOT NULL CONSTRAINT tb_AtributosDoBem_pk PRIMARY KEY,'
    +'id_patrimonio integer,'
    +'id_propriedade integer,'
    +'texto nvarchar(255),'
    +'dtInsercao datetime)',
'CREATE TABLE IF NOT EXISTS tb_InventarioMovimentacoes (id integer NOT NULL CONSTRAINT tb_InventarioMovimentacoes_pk PRIMARY KEY,'
    +'id_inventario integer,'
    +'id_propriedade integer,'
    +'valorAntigo nvarchar(255),'
    +'valorNovo nvarchar(255),'
    +'nome nvarchar(255),'
    +'dtInsercao datetime)',
'CREATE TABLE IF NOT EXISTS tb_PropriedadeLookUp (id integer NOT NULL CONSTRAINT tb_PropriedadeLookUp_pk PRIMARY KEY,'
    +'id_propriedade integer,'
    +'valor nvarchar(100),'
    +'situacao nvarchar(30),'
    +'dtInsercao datetime,'
    +'usuarioConfigLogin nvarchar(20),'
    +'retirar boolean,'
    +'temp boolean,'
    +'CONSTRAINT FK_tb_PropriedadeLookUp_tb_Propriedade FOREIGN KEY (id_propriedade) REFERENCES tb_Propriedade(id))',
'CREATE TABLE IF NOT EXISTS tb_TipoDado (id integer NOT NULL CONSTRAINT tb_TipoDado_pk PRIMARY KEY,'
    +'nome nvarchar(50))',
'CREATE TABLE IF NOT EXISTS tb_TipoDadosPatrimonio (id integer NOT NULL CONSTRAINT tb_TipoDadosPatrimonio_pk PRIMARY KEY,'
    +'codigo nvarchar(5),'
    +'descricao nvarchar(100))',
'CREATE TABLE IF NOT EXISTS tb_FotoDoBem (id integer NOT NULL CONSTRAINT tb_FotoDoBem_pk PRIMARY KEY,'
    +'codigoFilial nvarchar(20),'
    +'codigoPatrimonio nvarchar(20),'
    +'incorporacao integer,'
    +'nomeFoto nvarchar(100),'
    +'dtInsercao datetime,'
    +'syncToServer boolean)'    
];

export const tb_Marca = 'tb_Marca';
export const tb_Patrimonio = 'tb_Patrimonio';
export const tb_Inventario = 'tb_Inventario';
export const tb_CentroCusto = 'tb_CentroCusto';
export const tb_Local = 'tb_Local';
export const tb_Filial = 'tb_Filial';
export const tb_CondicaoUso = 'tb_CondicaoUso';
export const tb_Grupo = 'tb_Grupo';
export const tb_Propriedade = 'tb_Propriedade';
export const tb_CentroResponsabilidade = 'tb_CentroResponsabilidade';
export const tb_Especie = 'tb_Especie';
export const tb_DicionarioEspecie = 'tb_DicionarioEspecie';
export const tb_AtributosDoBem = 'tb_AtributosDoBem';
export const tb_InventarioMovimentacoes = 'tb_InventarioMovimentacoes';
export const tb_PropriedadeLookUp = 'tb_PropriedadeLookUp';
export const tb_TipoDado = 'tb_TipoDado';
export const tb_TipoDadosPatrimonio = 'tb_TipoDadosPatrimonio';
export const tb_FotoDoBem = 'tb_FotoDoBem';

export const tabelasPorData = ['tb_Filial','tb_Patrimonio','tb_Inventario','tb_Marca','tb_CentroCusto','tb_CentroResponsabilidade',
                                'tb_Local','tb_CondicaoUso','tb_Grupo','tb_Propriedade','tb_Especie','tb_DicionarioEspecie',
                                'tb_PropriedadeLookUp','tb_TipoDado','tb_TipoDadosPatrimonio',
                                'tb_AtributosDoBem','tb_InventarioMovimentacoes','tb_FotoDoBem'];

export const qtdLinhas = 10000;